project:
  type: book

book:
  title: "CAS_datascience_book"
  author: "Oliver Speer"
  date: "06.9.2023"
  cover-image: zhaw.png
  repo-url: https://github.com/oliverspeer/CAS-datascience.git
  repo-branch: main
  repo-actions: [edit, issue]
  
  chapters:
    - index.qmd
    - intro.qmd
    - part: ModulA.qmd
      chapters: 
        - day1.qmd
        - day2.qmd
        - LoesUeb03.qmd
        - LoesRUeb03.qmd
        - day3_1.qmd
        - LoesUeb05.qmd
        - Rexday3_1.qmd
        - Rexday3_2.qmd
        - LoesRUeb04.qmd
        - LoesRUeb05.qmd
        - ProbePruefA1.qmd
        - Prüfung230927.qmd
        - day4_1.qmd
    
    - part: ModulA2.qmd
      chapters: 
        - day3_2.qmd
        - LoesRHT1.qmd
        - day4.qmd
        - day5.qmd
        - LoesRHT2.qmd
        - day6.qmd
        - day7_1.qmd
        - LoesRHT3_4.qmd
        - LoesRHT5_6.qmd
        - LoesRHT7.qmd
        - ProbePruefA2.qmd
        - Prüfung231108.qmd
        
    - part: ModulB1.qmd
      chapters: 
        - day7_2.qmd
        - Uebungsblatt01.qmd
        - LoesB1_01.qmd
        - day8.qmd
        - Uebungsblatt02.qmd
        - LoesB1_02.qmd
        - day9.qmd
        - Uebungsblatt03.qmd
        - LoesB1_03.qmd
        - day10.qmd
        - Uebungsblatt04.qmd
        - LoesB1_04.qmd
        - day11.qmd
        - Uebungsblatt05.qmd
        - LoesB1_05.qmd
        
    - part: ModulB2.qmd
    
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    
    code-link: true
  pdf:
    documentclass: scrreprt
    
    author-meta: "Oliver Speer"
    callout-appearance: simple

editor: visual

